apps/models/products.py
from datetime import datetime
from .provider import Provider
from .company import Company
from apps import db


class Product(db.Model):
    __tablename__ = 'products'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    description = db.Column(db.Text, nullable=False)
    type = db.Column(db.String(30), nullable=False)
    category = db.Column(db.String(50), nullable=False)
    cost = db.Column(db.Numeric(10, 2), nullable=False)
    price = db.Column(db.Numeric(10, 2), nullable=False)
    status = db.Column(db.String(20), nullable=False)
    created = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated = db.Column(db.DateTime, nullable=False,
                        default=datetime.utcnow, onupdate=datetime.utcnow)
    supplier_id = db.Column(db.Integer, db.ForeignKey(
        'suppliers.id', onupdate='RESTRICT', ondelete='CASCADE'))
    company_id = db.Column(db.Integer, db.ForeignKey(
        'companies.id', onupdate='RESTRICT', ondelete='CASCADE'))

    supplier = db.relationship('Provider', backref=db.backref(
        'products', lazy=True))
    company = db.relationship('Company', backref=db.backref(
        'products', lazy=True))

    def __init__(self, description, type, category, cost, price, status, supplier, company):
        self.description = description
        self.type = type
        self.category = category
        self.cost = cost
        self.price = price
        self.status = status
        self.created = datetime.utcnow()
        self.updated = datetime.utcnow()
        self.supplier = supplier
        self.company = company

    def __repr__(self) -> str:
        return f'{self.description}'

apps/routes/product.py
from .auth import set_role
from flask import (
    render_template, Blueprint, flash, g, redirect, request, session, url_for
)

from werkzeug.security import generate_password_hash
from werkzeug.exceptions import BadRequestKeyError

from apps.models.products import Product
from apps.models.provider import Provider
from apps.models.company import Company
from apps.models.user import User
from apps import db

product = Blueprint('product', __name__, url_prefix='/product')


# función para verificar el rol del usuario

@product.route("/list")
# función para verificar el rol del usuario
@set_role
def get_product(user=None):
    products = Product.query.all()
    provider = Provider.query.all()
    company = Company.query.all()
    if g.role == 'Administrador':
        return render_template('admin/products/product/list.html', products=products, provider=provider, company=company)
    else:
        return render_template('views/products/product/list.html', products=products, provider=provider, company=company)


@product.route("/create", methods=['GET', 'POST'])
@set_role
def create_product(user=None):

    if request.method == "POST":
        try:
            description = request.form['description']
            type = request.form['type']
            category = request.form['category']
            cost = request.form['cost']
            price = request.form['price']
            status = request.form['status']
            supplier_id = request.form['supplier_id']
            company_id = request.form['company_id']

            # fetch the provider name from the database
            provider = Provider.query.filter_by(id=supplier_id).first()

            # fetch the company name from the database
            company = Company.query.filter_by(id=company_id).first()

            new_product = Product(
                description, type, category, cost, price, status, provider, company)

            db.session.add(new_product)
            db.session.commit()
            flash('¡Producto añadido con éxito!')
            return redirect(url_for('product.get_product'))

        except BadRequestKeyError as err:
            flash(f'Error: {str(err)}', category='error')
            return redirect(url_for('product.create_product'))

    company = Company.query.all()
    providers = Provider.query.all()
    if g.role == 'Administrador':
        return render_template('admin/products/product/create.html', company=company, providers=providers)
    else:
        return render_template('views/products/product/create.html', company=company, providers=providers)


@product.route("/update/<int:id>", methods=["GET", "POST"])
@set_role
def update_product(id, user=None):
    product = Product.query.get_or_404(id)

    if request.method == "POST":
        description = request.form['description']
        type = request.form['type']
        category = request.form['category']
        cost = request.form['cost']
        price = request.form['price']
        status = request.form['status']

        product.description = description
        product.type = type
        product.category = category
        product.cost = cost
        product.price = price
        product.status = status

        db.session.commit()

        flash('¡Producto actualizado con éxito!')
        return redirect(url_for('product.get_product'))

    if g.role == 'Administrador':
        return render_template('admin/products/product/update.html', product=product)
    else:
        return render_template('views/products/product/update.html', product=product)


@product.route("/delete/<int:id>", methods=["GET"])
@set_role
def delete_product(id, user=None):
    product = Product.query.get(id)

    if not product:
        flash('Producto no encontrado', category='error')
        return redirect(url_for('product.get_product'))

    try:
        db.session.delete(product)
        db.session.commit()

        flash('¡Producto eliminado con éxito!')
        return redirect(url_for('product.get_product'))

    except Exception as err:
        flash(
            f'Error al eliminar el producto: {str(err)}', category='error')
        return redirect(url_for('product.get_product'))

apps/templates/views/products/product/create.html
{% extends 'layout.html' %}
{% set current_page = 'Productos' %}
<h2>{% block title %}Nuevo Producto{% endblock %}</h2>

{% block content %}
<!-- Page Heading -->
<div class="d-sm-flex justify-content-end mb-4">
  <h1 class="h1 mb-0 text-gray-800 flex-grow-1">Productos</h1>
  <a href="{{url_for('product.get_product')}}" class="btn btn-primary btn-circle btn-lg m-1"
    title="Ver Todos los Productos">
    <i class="fas fa-list"></i>
  </a>
</div>
<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{url_for('product.get_product')}}">Productos</a></li>
    <li class="breadcrumb-item active" aria-current="page">Nuevo Producto</li>
  </ol>
</nav>

<!-- Content Row -->
<div class="card o-hidden border-0 shadow-lg my-5">
  <div class="card-body p-0">
    <!-- Nested Row within Card Body -->
    <div class="row">
      <div class="col-lg-12">
        <div class="p-5">
          <div class="text-left">
            <h3 class="text-gray-900 mb-4">Nuevo Producto</h3>
          </div>
          <form action="{{url_for('product.create_product')}}" method="POST">
            <div class="form-row">
              <div class="form-group col-md-12">
                <label for="description">Descripción</label>
                <input type="text" name="description" class="form-control rounded-imput">
              </div>
            </div>
            <div class="form-row">
              <div class="form-group col-md-4">
                <label for="type">Tipo</label>
                <select name="type" class="form-control rounded-imput">
                  <option value="" disabled selected></option>
                  <option value="Producto">Producto</option>
                  <option value="Servicio">Servicio</option>
                </select>
              </div>
              <div class="form-group col-md-8">
                <label for="category">Categoría</label>
                <select name="category" class="form-control js-example-basic-single">
                  <option value="" disabled selected></option>
                  <option value="Aceites y Lubricantes">Aceites y Lubricantes</option>
                  <option value="Adornos y Accesorios">Adornos y Accesorios</option>
                  <option value="Aire Acondicionado y Calefacción">Aire Acondicionado y Calefacción</option>
                  <option value="Carga y Remolque">Carga y Remolque</option>
                  <option value="Carrocería">Carrocería</option>
                  <option value="Combustible">Combustible</option>
                  <option value="Diagnóstico">Diagnóstico</option>
                  <option value="Frenos">Frenos</option>
                  <option value="Herramientas">Herramientas</option>
                  <option value="Iluminación">Iluminación</option>
                  <option value="Limpieza">Limpieza</option>
                  <option value="Motor y Escape">Motor y Escape</option>
                  <option value="Neumáticos">Neumáticos</option>
                  <option value="Pintura">Pintura</option>
                  <option value="Seguridad">Seguridad</option>
                  <option value="Sistema de Electricidad y Encendido">Sistema de Electricidad y Encendido</option>
                  <option value="Sonido y Multimedia">Sonido y Multimedia</option>
                  <option value="Suspensión">Suspensión</option>
                  <option value="Transmisión">Transmisión</option>
                  <option value="Otros">Otros</option>
                </select>
              </div>
            </div>
            <div class="form-row">
              <div class="form-group col-md-4">
                <label for="cost">Costo</label>
                <input type="number" name="cost" class="form-control rounded-select">
              </div>
              <div class="form-group col-md-4">
                <label for="price">Precio</label>
                <input type="number" name="price" class="form-control rounded-select">
              </div>
              <div class="form-group col-md-4">
                <label for="status">Estado</label>
                <select name="status" class="form-control rounded-select">
                  <option value="" disabled selected></option>
                  <option value="Activo">Activo</option>
                  <option value="Inactivo">Inactivo</option>
                </select>
              </div>
            </div>
            <div class="form-row">
              <div class="form-group col-md-6">
                <label for="supplier_id">Proveedor</label>
                <select name="supplier_id" class="form-control js-example-basic-single">
                  <option value="" selected disabled></option>
                  <option value="0">Ninguno</option>
                  {% for provider in providers%}
                  <option value="{{provider.id}}">{{provider.trade_name}}</option>
                  {% endfor %}
                </select>
              </div>
              <div class="form-group col-md-6">
                <label for="company_id">Empresa</label>
                <select name="company_id" class="form-control js-example-basic-single">
                  <option value="" selected disabled></option>
                  {% for company in company%}
                  <option value="{{company.id}}">{{company.trade_name}}</option>
                  {% endfor %}
                </select>
              </div>
            </div>
            <div class="col-12 text-center">
              <button class="btn btn-primary col-6 rounded-button" type="submit">Crear</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

apps/templates/views/products/product/list.html
{% extends 'layout.html' %}
{% set current_page = 'Productos' %}
<h2>{% block title %}Productos{% endblock %}</h2>

{% block content %}
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h1 mb-0 text-gray-800 d-flex">Productos</h1>
    <a href="{{url_for('product.create_product')}}" class="btn btn-primary btn-circle btn-lg ml-auto" title="Nuevo Producto">
        <i class="fa fa-plus" aria-hidden="true"></i>
    </a>
</div>
<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">Productos</li>
    </ol>
</nav>
<!-- Content Row -->

<!-- DataTales Example -->
<div class="card shadow mb-5">
    <div class="card-header py-2">
        <h3 class="text-gray-900 mb-4">Todos los Productos</h3>
    </div>
    <div class="card-body table-custom">
        <div class="table-responsive">
            <table class="table" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th class="th-sm">Descripción
                        </th>
                        <th class="th-sm">Tipo
                        </th>
                        <th class="th-sm">Categoría
                        </th>
                        <th class="th-sm">Costo
                        </th>
                        <th class="th-sm">Precio
                        </th>
                        <th class="th-sm">Estado
                        </th>
                        <th class="th-sm">Creado
                        </th>
                        <th class="th-sm">Actualizado
                        </th>
                        <th class="th-sm">Proveedor
                        </th>
                        <th class="th-sm">Empresa
                        </th>
                        <th class="th-sm">Acciones
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {%for product in products%}
                    <tr>
                        <td>{{product.description}}</td>
                        <td>{{product.type}}</td>
                        <td>{{product.category}}</td>
                        <td>{{product.cost}}</td>
                        <td>{{product.price}}</td>
                        <td>
                            {% set state_colors = {'Activo': 'badge-success', 'Inactivo': 'badge-danger'} %}
                            {% set state_color = state_colors.get(product.status, 'badge-secondary') %}
                            <span class="badge {{state_color}}">{{product.status}}</span>
                        </td>
                        <td>{{product.created}}</td>
                        <td>{{product.updated}}</td>
                        <td>{{product.supplier|default('Ninguno',true)}}</td>
                        <td>{{product.company}}</td>
                        <td>
                            <button class="btn  btn-sm btn-primary" onclick="location.href='{{ url_for('product.update_product', id=product.id) }}'" title="Editar">
                                <i class="fa fa-edit"></i>
                            </button>
                            <button class="btn btn-sm btn-danger"
                                onclick="location.href='{{ url_for('product.delete_product', id=product.id) }}'" title="Eliminar">
                                <i class="fa fa-trash"></i>
                            </button>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- </div> -->

{% endblock %}

apps/templates/views/products/product/update.html
{% extends 'layout.html' %}
{% set current_page = 'Productos' %}
<h2>{% block title %}Editar Producto{% endblock %}</h2>

{% block content %}
<!-- Page Heading -->
<div class="d-sm-flex justify-content-end mb-4">
  <h1 class="h1 mb-0 text-gray-800 flex-grow-1">Productos</h1>
  <a href="{{url_for('product.get_product')}}" class="btn btn-primary btn-circle btn-lg m-1" title="Ver Todos los Productos">
      <i class="fas fa-list"></i>
  </a>
</div>
<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{url_for('product.get_product')}}">Productos</a></li>
    <li class="breadcrumb-item active" aria-current="page">Editar Producto</li>
  </ol>
</nav>

<!-- Content Row -->
<div class="card o-hidden border-0 shadow-lg my-5">
  <div class="card-body p-0">
    <!-- Nested Row within Card Body -->
    <div class="row">
      <div class="col-lg-12">
        <div class="p-5">
          <div class="text-left">
            <h3 class="text-gray-900 mb-4">Editar Producto</h3>
          </div>
          <form action="{{url_for('product.update_product', id=product.id)}}" method="POST">
            <div class="form-row">
              <div class="form-group col-md-12">
                <label for="description">Descripción</label>
                <input type="text" name="description" class="form-control rounded-imput" value="{{product.description}}">
              </div>
            </div>
            <div class="form-row">
              <div class="form-group col-md-4">
                <label for="type">Tipo</label>
                <select name="type" class="form-control rounded-imput">
                  <option value="" {% if not product.type %}selected{% endif %} disabled></option>
                  <option value="Producto" {% if product.type=="Producto" %}selected{% endif %}>Producto</option>
                  <option value="Servicio" {% if product.type=="Servicio" %}selected{% endif %}>Servicio</option>
                </select>
              </div>
              <div class="form-group col-md-8">
                <label for="category">Categoría</label>
                <select name="category" class="form-control js-example-basic-single">
                  <option value="" {% if not product.category %}selected{% endif %} disabled></option>
                  <option value="Aceites y Lubricantes" {% if product.category=="Aceites y Lubricantes" %}selected{% endif %}>Aceites y Lubricantes</option>
                  <option value="Adornos y Accesorios" {% if product.category=="Adornos y Accesorios" %}selected{% endif %}>Adornos y Accesorios</option>
                  <option value="Aire Acondicionado y Calefacción" {% if product.category=="Aire Acondicionado y Calefacción" %}selected{% endif %}>Aire Acondicionado y Calefacción</option>
                  <option value="Carga y Remolque" {% if product.category=="Carga y Remolque" %}selected{% endif %}>Carga y Remolque</option>
                  <option value="Carrocería" {% if product.category=="Carrocería" %}selected{% endif %}>Carrocería</option>
                  <option value="Combustible" {% if product.category=="Combustible" %}selected{% endif %}>Combustible</option>
                  <option value="Diagnóstico" {% if product.category=="Diagnóstico" %}selected{% endif %}>Diagnóstico</option>
                  <option value="Frenos" {% if product.category=="Frenos" %}selected{% endif %}>Frenos</option>
                  <option value="Herramientas" {% if product.category=="Herramientas" %}selected{% endif %}>Herramientas</option>
                  <option value="Iluminación" {% if product.category=="Iluminación" %}selected{% endif %}>Iluminación</option>
                  <option value="Limpieza" {% if product.category=="Limpieza" %}selected{% endif %}>Limpieza</option>
                  <option value="Motor y Escape" {% if product.category=="Motor y Escape" %}selected{% endif %}>Motor y Escape</option>
                  <option value="Neumáticos" {% if product.category=="Neumáticos" %}selected{% endif %}>Neumáticos</option>
                  <option value="Pintura" {% if product.category=="Pintura" %}selected{% endif %}>Pintura</option>
                  <option value="Seguridad" {% if product.category=="Seguridad" %}selected{% endif %}>Seguridad</option>
                  <option value="Sistema de Electricidad y Encendido" {% if product.category=="Sistema de Electricidad y Encendido" %}selected{% endif %}>Sistema de Electricidad y Encendido</option>
                  <option value="Sonido y Multimedia" {% if product.category=="Sonido y Multimedia" %}selected{% endif %}>Sonido y Multimedia</option>
                  <option value="Suspensión" {% if product.category=="Suspensión" %}selected{% endif %}>Suspensión</option>
                  <option value="Transmisión" {% if product.category=="Transmisión" %}selected{% endif %}>Transmisión</option>
                  <option value="Otros" {% if product.category=="Otros" %}selected{% endif %}>Otros</option>                  
                </select>
              </div>
            </div>
            <div class="form-row">
              <div class="form-group col-md-4">
                <label for="cost">Costo</label>
                <input type="number" name="cost" class="form-control rounded-select" value="{{product.cost}}">
              </div>
              <div class="form-group col-md-4">
                <label for="price">Precio</label>
                <input type="number" name="price" class="form-control rounded-select" value="{{product.price}}">
              </div>
              <div class="form-group col-md-4">
                <label for="status">Estado</label>
                <select name="status" class="form-control rounded-select">
                  <option value="Activo" {% if product.status=="Activo" %}selected{% endif %}>Activo</option>
                  <option value="Inactivo" {% if product.status=="Inactivo" %}selected{% endif %}>Inactivo</option>
                </select>
              </div>
            </div>
            <div class="form-row">
              <div class="form-group col-md-6">
                <label for="supplier_id">Proveedor</label>
                <select name="supplier_id" class="form-control js-example-basic-single" disabled>
                  <option value="{{product.supplier_id}}" selected>{{product.supplier}}</option>
                </select>
              </div>
              <div class="form-group col-md-6">
                <label for="company_id">Empresa</label>
                <select name="company_id" class="form-control js-example-basic-single" disabled>
                  <option value="{{product.company_id}}" selected>{{product.company}}</option>
                </select>
              </div>
            </div>
            <div class="col-12 text-center">
              <button class="btn btn-primary col-6 rounded-button" type="submit">Actualizar</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}