apps/models/shopping.py
from datetime import datetime
from apps import db
from .inventory import Inventory
from .company import Company
from .provider import Provider
from .products import Product


class Shopping(db.Model):
    __tablename__ = 'shoppings'
    id = db.Column(db.Integer, primary_key=True)
    order_num = db.Column(db.String(20), unique=True)
    total = db.Column(db.Numeric(10, 2))
    created = db.Column(db.DateTime, nullable=False, default=datetime.utcnow,)
    company_id = db.Column(db.Integer, db.ForeignKey(
        'companies.id', onupdate='RESTRICT', ondelete='CASCADE'))
    company = db.relationship(
        'Company', backref=db.backref('shoppings', lazy=True))
    provider_id = db.Column(db.Integer, db.ForeignKey(
        'suppliers.id', onupdate='RESTRICT', ondelete='CASCADE'))
    provider = db.relationship(
        'Provider', backref=db.backref('shoppings', lazy=True))
    details = db.relationship('ShoppingDetail', backref='shoppings', lazy=True)

    def __init__(self, order_num, total, company, provider):
        self.order_num = order_num
        self.total = total
        self.created = datetime.utcnow()
        self.company = company
        self.provider = provider
        
        
    def update_inventory(self):
        for detail in self.details:
            inventory = Inventory.query.filter_by(product_id=detail.product_id).first()
            if inventory:
                inventory.set_stock += detail.quantity
                db.session.commit()

    @staticmethod
    def numero_orden_existe_en_bd(order_num):
        # Verificar si el número de orden ya existe en la base de datos
        order = Shopping.query.filter_by(order_num=order_num).first()
        if order:
            return True
        else:
            return False


class ShoppingDetail(db.Model):
    __tablename__ = 'shoppings_details'
    id = db.Column(db.Integer, primary_key=True)
    product_id = db.Column(db.Integer, db.ForeignKey(
        'products.id'), nullable=False)
    product = db.relationship(
        'Product', backref=db.backref('shoppings_details', lazy=True))
    quantity = db.Column(db.Integer, nullable=False)
    unt_cost = db.Column(db.Float, nullable=False)
    total_cost = db.Column(db.Float, nullable=False)
    shopping_id = db.Column(db.Integer, db.ForeignKey(
        'shoppings.id'), nullable=False)

    def __init__(self, shopping_id, quantity, unt_cost, total_cost, product_id):
        self.shopping_id = shopping_id
        self.product_id = product_id
        self.quantity = quantity
        self.unt_cost = unt_cost
        self.total_cost = total_cost

apps/routes/shopping.py
from flask import (
    render_template, Blueprint, flash, g, redirect, request, session, url_for, Response
)
# Importar el contador
from itertools import count
from werkzeug.security import generate_password_hash

# from apps.models.shopping import shopping
from apps.models.user import User
from apps import db
from .auth import set_role
from apps.models.company import Company
from apps.models.shopping import Shopping, ShoppingDetail
from apps.models.provider import Provider
from apps.models.products import Product
from apps.models.inventory import Inventory

from io import BytesIO
from reportlab.pdfgen import canvas

shopping = Blueprint('shopping', __name__, url_prefix='/shopping')


@shopping.route("/list")
# función para verificar el rol del usuario
@set_role
def get_shopping(user=None):
    shopping = Shopping.query.all()
    if g.role == 'Administrador':
        return render_template('admin/workshop/shopping/list.html', shopping=shopping)
    else:
        return render_template('views/workshop/shopping/list.html', shopping=shopping)


@shopping.route("/create", methods=['GET', 'POST'])
@set_role
def create_shopping(user=None):
    if request.method == 'POST':
        company_id = request.form['company_id']
        provider_id = request.form['provider_id']
        # order_num = "FT-" + str(next(order_num_counter))
        company = Company.query.filter_by(id=company_id).first()
        provider = Provider.query.filter_by(id=provider_id).first()
        # Obtener una lista de los valores del campo "detalle"
        detalles = request.form.getlist('detalle')
        # Obtener una lista de los valores del campo "cantidad"
        cantidades = request.form.getlist('cantidad')
        # Obtener una lista de los valores del campo "precio_unitario"
        precios_unitarios = request.form.getlist('precio_unitario')
        # Obtener una lista de los valores del campo "subtotal"
        precios_totales = request.form.getlist('subtotal')
        subtotal = []
        for num in precios_totales:
            try:
                subtotal.append(float(num))
            except ValueError:
                pass
        total = sum(subtotal)

        # Generar un nuevo número de orden
        # Crear un contador que inicie en 100
        order_num_counter_service = count(start=100)
        order_num = "CM-" + str(next(order_num_counter_service))

        # Verificar si el número de orden ya existe en la base de datos
        while Shopping.numero_orden_existe_en_bd(order_num):
            order_num = "CM-" + str(next(order_num_counter_service))

        new_shopping = Shopping(
            total=total, order_num=order_num, company=company, provider=provider)
        new_shopping.details = []

        db.session.add(new_shopping)
        db.session.commit()
        # Procesar los detalles de la compra
        for i in range(len(detalles)):
            shopping_id = new_shopping.id
            product_id = detalles[i]
            quantity = cantidades[i]
            unt_cost = precios_unitarios[i]
            total_cost = precios_totales[i]

            new_detail = ShoppingDetail(
                shopping_id=shopping_id, product_id=product_id, quantity=quantity, unt_cost=unt_cost, total_cost=total_cost)
            new_shopping.details.append(new_detail)
            db.session.add(new_detail)
        db.session.commit()  # Commit después de agregar todos los detalles
        new_shopping.update_inventory()

        flash('Compra creada exitosamente')
        return redirect(url_for('shopping.ready_shopping'))
    companies = Company.query.all()
    provider = Provider.query.all()
    product = db.session.query(Product).join(Inventory).filter(
        Inventory.set_stock > 0).all()
    if g.role == 'Administrador':
        return render_template('admin/workshop/shopping/create.html', companies=companies, product=product, provider=provider)
    else:
        return render_template('views/workshop/shopping/create.html', companies=companies, product=product, provider=provider)


@shopping.route("/done")
# función para verificar el rol del usuario
@set_role
def ready_shopping(user=None):
    ultimo_id = Shopping.query.order_by(db.desc(Shopping.id)).first().id
    if g.role == 'Administrador':
        return render_template('admin/workshop/shopping/done.html', ultimo_id=ultimo_id)
    else:
        return render_template('views/workshop/shopping/done.html', ultimo_id=ultimo_id)


@shopping.route("/delete/<int:id>", methods=["GET"])
@set_role
def delete_shopping(id, user=None):
    shoppings = Shopping.query.get(id)

    if not shoppings:
        flash('Compra no encontrada', category='error')
        return redirect(url_for('shopping.get_shopping'))

    try:
        # Obtener los registros relacionados en la tabla de los detalles
        shoppings_details = ShoppingDetail.query.filter_by(
            shopping_id=id).all()

        # Eliminar los registros en la tabla de los detalles
        for shopping_detail in shoppings_details:
            db.session.delete(shopping_detail)

        # Confirmar los cambios en la base de datos
        db.session.commit()

        # Eliminar la recepción de vehículo
        db.session.delete(shoppings)
        db.session.commit()

        flash('¡Compra eliminada con éxito!')
        return redirect(url_for('shopping.get_shopping'))

    except Exception as err:
        db.session.rollback()  # Deshacer los cambios en caso de error
        flash(
            f'Error al eliminar la compra: {str(err)}', category='error')
        return redirect(url_for('shopping.get_shopping'))


@shopping.route("/print/<int:id>", methods=["GET"])
@set_role
def print_shopping(id, user=None):
    shopping = Shopping.query.get(id)
    detalles = ShoppingDetail.query.filter_by(shopping_id=id).all()

    # Crear el documento PDF utilizando ReportLab
    buffer = BytesIO()
    pdf = canvas.Canvas(buffer)

    # Agregar la información de la factura al documento
    pdf.drawString(270, 750, f'{shopping.company}')
    pdf.drawString(275, 725, 'Compra')
    pdf.drawString(60, 700, f'{shopping.order_num}')
    pdf.drawString(60, 675, f'Proveedor: {shopping.provider}')

    # Agregar los detalles de la factura al documento
    pdf.drawString(60, 630, 'Descripción')
    pdf.drawString(300, 630, 'Cantidad')
    pdf.drawString(380, 630, 'Costo Unitario')
    pdf.drawString(480, 630, 'Costo Total')
    y = 600
    for detalle in detalles:
        product = detalle.product
        quantity = detalle.quantity
        unt_cost = detalle.unt_cost
        total_cost = detalle.total_cost
        pdf.drawString(300, y, f'{quantity}')
        pdf.drawString(60, y, f'{product}')
        pdf.drawString(380, y, f'{unt_cost}')
        pdf.drawString(480, y, f'{total_cost}')
        y -= 30

    pdf.drawString(400, 200, f'Total de la Compra: {shopping.total}')

    # Guardar y cerrar el documento
    pdf.showPage()
    pdf.save()

    # Generar la respuesta con el PDF generado
    buffer.seek(0)
    response = Response(buffer.getvalue(), mimetype='application/pdf')
    response.headers['Content-Disposition'] = f'inline; filename=compra_{shopping.id}.pdf'
    return response

apps/templates/views/workshop/shopping/create.html
{% extends 'layout.html' %}
{% set current_page = 'Taller' %}
<h2>{% block title %}Compras{% endblock %}</h2>

{% block content %}
<!-- Page Heading -->
<div class="d-sm-flex justify-content-end mb-4">
    <h1 class="h1 mb-0 text-gray-800 flex-grow-1">Compras</h1>
    <a href="{{url_for('shopping.get_shopping')}}" class="btn btn-primary btn-circle btn-lg m-1"
        title="Ver Historial de Compras">
        <i class="fas fa-list"></i>
    </a>
</div>
<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">Compras</li>
    </ol>
</nav>
<!-- Content Row -->
<div class="card o-hidden border-0 shadow-lg my-5">
    <div class="card-body p-0">
        <!-- New Row Form cabecera de factura -->
        <div class="row">
            <div class="col-lg-12">
                <div class="p-5">
                    <div class="text-left">
                        <h3 class="text-gray-900 mb-4">Nueva Compra</h3>
                        <form method="post" action="{{url_for('shopping.create_shopping')}}">
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label for="">Datos del Proveedor</label>
                                    <select id="provider_id" name="provider_id"
                                        class="form-control js-example-basic-single">
                                        <option value="" disabled selected></option>
                                        {% for provider in provider %}
                                        <option value="{{ provider.id }}">{{ provider.trade_name }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="company_id">Datos de la Empresa</label>
                                    <select id="company_id" name="company_id"
                                        class="form-control rounded-select js-example-basic-single">
                                        <option value="" disabled selected></option>
                                        {% for company in companies %}
                                        <option value="{{ company.id }}">{{ company.trade_name }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <br>
                            <h3 class="text-gray-900 mb-4">Detalle de la Compra</h3>
                            <table id="tabla-detalles">
                                <tr>
                                    <th>Producto</th>
                                    <th>Cantidad</th>
                                    <th>Costo Unitario</th>
                                    <th>Costo Total</th>
                                </tr>
                                <tr>
                                    <td><select class="form-control js-example-basic-single" name="detalle" id="detalle"
                                            onchange="cargarPrecioUnitario(this)">
                                            <option value="0" selected disabled></option>
                                            {% for product in product %}
                                            <option value="{{ product['id'] }}" data-unit-price="{{ product['cost']}}">
                                                {{product["description"] }}
                                            </option>
                                            {% endfor %}
                                        </select></td>
                                    <td><input type="number" name="cantidad" class="form-control"
                                            oninput="calcularSubtotal(this)" required min="1"></td>
                                    <td><input type="number" name="precio_unitario" class="form-control"
                                            oninput="calcularSubtotal(this)" readonly></td>
                                    <td><input type="number" name="subtotal" oninput="calcularSubtotal(this)"
                                            class="form-control" readonly></td>
                                </tr>
                            </table>
                            <br>
                            <input type="button" value="Agregar Producto" class="btn btn-primary rounded-button"
                                onclick="agregarDetalle()">
                            <!-- Botón para agregar detalle -->
                            <br>
                            <div class="col-12 text-center">
                                <input type="submit" class="btn btn-primary col-6 rounded-button" value="Comprar">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>

    // Función para agregar una nueva fila a la tabla
    function agregarDetalle() {

        var fila = '<tr>' +
            '<td><select class="form-control js-example-basic-single" name="detalle" id="detalle" onchange="cargarPrecioUnitario(this)">' +
            '<option value="0" selected disabled></option>{% for product in product %}<option value="{{ product["id"] }}" data-unit-price="{{ product["cost"] }}">{{product["description"] }}</option>{% endfor %}</select></td>' +
            '<td><input type="number" name="cantidad" class="form-control" oninput="calcularSubtotal(this)" required></td>' +
            '<td><input type="number" name="precio_unitario" class="form-control" oninput="calcularSubtotal(this)" readonly></td>' +
            '<td><input type="number" name="subtotal"  class="form-control" oninput="calcularSubtotal(this)" readonly></td>' +
            '<td><button type="button" class="btn btn-danger" onclick="eliminarFila(this)"><i class="fa fa-trash"></i></button></td>' + // Agrega un botón de eliminación
            '</tr>';
        $('#tabla-detalles').append(fila);
        sumarCantidad(); // Agregar esta línea para llamar a la función sumarCantidad() después de agregar la nueva fila
    }

    // Función para eliminar una fila de la tabla
    function eliminarFila(buttonElement) {
        var fila = $(buttonElement).closest('tr');
        fila.remove();
        sumarCantidad(); // Llama a la función sumarCantidad() después de eliminar la fila
    }

    // Función para cargar el precio unitario en base al producto seleccionado
    function cargarPrecioUnitario(selectElement) {
        var unitPrice = selectElement.options[selectElement.selectedIndex].getAttribute('data-unit-price');
        var row = selectElement.parentNode.parentNode;
        var precioUnitarioInput = row.querySelector('input[name="precio_unitario"]');
        precioUnitarioInput.value = unitPrice;
    }

    // Función para calcular el subtotal en base a la cantidad y precio unitario ingresados
    function calcularSubtotal(inputElement) {
        var row = inputElement.parentNode.parentNode;
        var cantidadInput = row.querySelector('input[name="cantidad"]');
        var subtotalInput = row.querySelector('input[name="subtotal"]');
        var cantidad = cantidadInput.value;
        var precioUnitario = row.querySelector('input[name="precio_unitario"]').value;
        var subtotal = precioUnitario * cantidad;
        subtotalInput.value = subtotal;
    }

    // Función para sumar la cantidad si es el mismo producto y no agregar una fila nueva
    function sumarCantidad() {
        var detalleSelects = document.getElementsByName('detalle');
        var detalleArray = Array.from(detalleSelects);
        var selectedValues = detalleArray.map(function (selectElement) {
            return selectElement.value;
        });
        var duplicados = selectedValues.filter(function (value, index, self) {
            return self.indexOf(value) !== index;
        });

        duplicados.forEach(function (value) {
            var filas = $('#tabla-detalles tr');
            var subtotal = 0;
            filas.each(function () {
                var detalle = $(this).find('select[name="detalle"]').val();
                var cantidad = parseInt($(this).find('input[name="cantidad"]').val());
                if (detalle === value) {
                    subtotal += cantidad;
                    $(this).remove();
                }
            });

            var nuevaFila = $('#tabla-detalles tr:last');
            var nuevoSelect = nuevaFila.find('select[name="detalle"]');
            nuevoSelect.val(value);
            nuevoSelect.change();
            nuevaFila.find('input[name="cantidad"]').val(subtotal);
            calcularSubtotal(nuevaFila.find('input[name="cantidad"]')[0]);
        });
    }
</script>

{% endblock %}

apps/templates/views/workshop/shopping/done.html
{% extends 'layout.html' %}
{% set current_page = 'Taller' %}
context = {'ultimo_id': ultimo_id}
<h2>{% block title %}Historial de Compras{% endblock %}</h2>

{% block content %}
<!-- Page Heading -->
<h1 class="h1 mb-0 text-gray-800 d-flex">Compras</h1>
<br>
<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{url_for('shopping.create_shopping')}}">Compras</a></li>
        <li class="breadcrumb-item active" aria-current="page">Compra Emitida</li>
    </ol>
</nav>
<!-- Content Row -->

<!-- DataTales Example -->
<div class="card shadow mb-5">
    <div class="card-body p-0">
        <!-- New Row Form cabecera de factura -->
        <div class="row">
            <div class="col-lg-12">
                <div class="p-5">
                    <div class="col-12 text-center">
                        <img src="{{url_for('static', filename='img/check.png')}}" alt="" width="150">
                        <h1 class="mb-4">Compra Emitida</h1>
                        <a href="{{ url_for('shopping.print_shopping', id=ultimo_id) }}" class="btn btn-primary col-2 rounded-button">Imprimir Compra</a>
                        <a href="{{url_for('shopping.create_shopping')}}" class="btn btn-secondary col-2 rounded-button">Volver a Compras</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- </div> -->

{% endblock %}

apps/templates/views/workshop/shopping/list.html
{% extends 'layout.html' %}
{% set current_page = 'Taller' %}
<h2>{% block title %}Historial de Compras{% endblock %}</h2>

{% block content %}
<!-- Page Heading -->
<h1 class="h1 mb-0 text-gray-800 d-flex"></h1>
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h1 mb-0 text-gray-800 flex-grow-1">Compras</h1>
    <a href="{{url_for('shopping.create_shopping')}}" class="btn btn-primary btn-circle btn-lg ml-auto" title="Nueva Compra">
        <i class="fa fa-plus" aria-hidden="true"></i>
    </a>
</div>
<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{url_for('shopping.create_shopping')}}">Compras</a></li>
        <li class="breadcrumb-item active" aria-current="page">Historial de Compras</li>
    </ol>
</nav>
<!-- Content Row -->

<!-- DataTales Example -->
<div class="card shadow mb-5">
    <div class="card-header py-2">
        <h3 class="text-gray-900 mb-4">Historial de Compras</h3>
    </div>
    <div class="card-body table-custom">
        <div class="table-responsive">
            <blockquote>Pulsa en "Imprimir" en la compra deseada para ver más información.</blockquote>
            <table class="table" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>No. de Compra</th>
                        <th>Proveedor</th>
                        <th>Total</th>
                        <th>Creada</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for shopping in shopping%}
                    <tr>
                        <td>{{shopping.order_num}}</td>
                        <td>{{shopping.provider}}</td>
                        <td>{{shopping.total}}</td>
                        <td>{{shopping.created}}</td>
                        <td>
                            <button class="btn  btn-sm btn-primary" onclick="location.href='{{ url_for('shopping.print_shopping', id=shopping.id) }}'" title="Imprimir">
                                <i class="fa fa-print"></i>
                            </button>
                            <button class="btn btn-sm btn-danger"
                                onclick="location.href='{{ url_for('shopping.delete_shopping', id=shopping.id) }}'" title="Eliminar">
                                <i class="fa fa-trash"></i>
                            </button>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- </div> -->

{% endblock %}