apps/models/inventory.py
from datetime import datetime
from .products import Product
from apps import db

class Inventory(db.Model):
    __tablename__ = 'inventories'

    id=db.Column(db.Integer,primary_key=True, autoincrement=True)
    min_stock=db.Column(db.Integer, nullable=False)
    set_stock=db.Column(db.Integer, nullable=False)
    type=db.Column(db.String(50), nullable=False)
    location=db.Column(db.String(100), nullable=False)
    created = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated = db.Column(db.DateTime, nullable=False, default=datetime.utcnow, onupdate=datetime.utcnow)
    product_id = db.Column(db.Integer, db.ForeignKey('products.id', onupdate='restrict', ondelete='cascade'))
    product = db.relationship('Product', backref=db.backref('inventories', lazy=True))

    def __init__(self, min_stock, set_stock ,type ,location ,product):
        self.min_stock=min_stock
        self.set_stock=set_stock
        self.type=type
        self.location=location
        self.created = datetime.utcnow()
        self.updated = datetime.utcnow()
        self.product=product

apps/models/products.py
from datetime import datetime
from .provider import Provider
from .company import Company
from apps import db


class Product(db.Model):
    __tablename__ = 'products'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    description = db.Column(db.Text, nullable=False)
    type = db.Column(db.String(30), nullable=False)
    category = db.Column(db.String(50), nullable=False)
    cost = db.Column(db.Numeric(10, 2), nullable=False)
    price = db.Column(db.Numeric(10, 2), nullable=False)
    status = db.Column(db.String(20), nullable=False)
    created = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated = db.Column(db.DateTime, nullable=False,
                        default=datetime.utcnow, onupdate=datetime.utcnow)
    supplier_id = db.Column(db.Integer, db.ForeignKey(
        'suppliers.id', onupdate='RESTRICT', ondelete='CASCADE'))
    company_id = db.Column(db.Integer, db.ForeignKey(
        'companies.id', onupdate='RESTRICT', ondelete='CASCADE'))

    supplier = db.relationship('Provider', backref=db.backref(
        'products', lazy=True))
    company = db.relationship('Company', backref=db.backref(
        'products', lazy=True))

    def __init__(self, description, type, category, cost, price, status, supplier, company):
        self.description = description
        self.type = type
        self.category = category
        self.cost = cost
        self.price = price
        self.status = status
        self.created = datetime.utcnow()
        self.updated = datetime.utcnow()
        self.supplier = supplier
        self.company = company

    def __repr__(self) -> str:
        return f'{self.description}'

apps/routes/inventory.py
from .auth import set_role
from flask import (
    render_template, Blueprint, flash, g, redirect, request, session, url_for
)

from werkzeug.security import generate_password_hash
from werkzeug.exceptions import BadRequestKeyError

from apps.models.user import User
from apps.models.products import Product
from apps.models.inventory import Inventory
from apps import db

inventory = Blueprint('inventory', __name__, url_prefix='/inventory')


@inventory.route("/list")
# función para verificar el rol del usuario
@set_role
def get_inventory(user=None):
    inventory = Inventory.query.all()
    if g.role == 'Administrador':
        return render_template('admin/products/inventory/list.html', inventory=inventory)
    else:
        return render_template('views/products/inventory/list.html', inventory=inventory)

@inventory.route("/create", methods=['GET', 'POST'])
@set_role
def create_inventory(user=None):
    products = Product.query.filter(Product.type=='Producto').filter(Product.status=='Activo').all()

    if request.method == "POST":
            min_stock = request.form['min_stock']
            set_stock = request.form['set_stock']
            type = request.form['type']
            location = request.form['location']
            product_id = request.form['product_id']
            
            product = Product.query.filter_by(id=product_id).first()

            new_inventory=Inventory(min_stock=min_stock, set_stock=set_stock, type=type, location=location, product=product)

            db.session.add(new_inventory)
            db.session.commit()
            flash('¡Producto añadido al inventario con éxito!')
            return redirect(url_for('inventory.get_inventory'))
        
    if g.role == 'Administrador':
        return render_template('admin/products/inventory/create.html', products=products)
    else:
        return render_template('views/products/inventory/create.html', products=products)

@inventory.route("/update/<int:id>", methods=["GET", "POST"])
@set_role
def update_inventory(id, user=None):
     inventory=Inventory.query.get_or_404(id)

     if request.method == "POST":
            min_stock = request.form['min_stock']
            set_stock = request.form['set_stock']
            type = request.form['type']
            location = request.form['location']

            inventory.min_stock=min_stock
            inventory.set_stock=set_stock
            inventory.type=type
            inventory.location=location

            db.session.commit()

            flash('¡Producto en inventario actualizado con éxito!')
            return redirect(url_for('inventory.get_inventory'))
      
     if g.role == 'Administrador':
        return render_template('admin/products/inventory/update.html', inventory=inventory)
     else:
          return render_template('views/products/inventory/update.html', inventory=inventory)



@inventory.route("/delete/<int:id>", methods=["GET"])
@set_role
def delete_inventory(id, user=None):
    inventory = Inventory.query.get(id)

    if not inventory:
        flash('Producto no encontrado en inventario', category='error')
        return redirect(url_for('inventory.get_inventory'))

    try:
        db.session.delete(inventory)
        db.session.commit()

        flash('¡Producto eliminado con éxito del inventario!')
        return redirect(url_for('inventory.get_inventory'))

    except Exception as err:
        flash(
            f'Error al eliminar el producto de inventario: {str(err)}', category='error')
        return redirect(url_for('inventory.get_inventory'))

apps/routes/product.py
from .auth import set_role
from flask import (
    render_template, Blueprint, flash, g, redirect, request, session, url_for
)

from werkzeug.security import generate_password_hash
from werkzeug.exceptions import BadRequestKeyError

from apps.models.products import Product
from apps.models.provider import Provider
from apps.models.company import Company
from apps.models.user import User
from apps import db

product = Blueprint('product', __name__, url_prefix='/product')


# función para verificar el rol del usuario

@product.route("/list")
# función para verificar el rol del usuario
@set_role
def get_product(user=None):
    products = Product.query.all()
    provider = Provider.query.all()
    company = Company.query.all()
    if g.role == 'Administrador':
        return render_template('admin/products/product/list.html', products=products, provider=provider, company=company)
    else:
        return render_template('views/products/product/list.html', products=products, provider=provider, company=company)


@product.route("/create", methods=['GET', 'POST'])
@set_role
def create_product(user=None):

    if request.method == "POST":
        try:
            description = request.form['description']
            type = request.form['type']
            category = request.form['category']
            cost = request.form['cost']
            price = request.form['price']
            status = request.form['status']
            supplier_id = request.form['supplier_id']
            company_id = request.form['company_id']

            # fetch the provider name from the database
            provider = Provider.query.filter_by(id=supplier_id).first()

            # fetch the company name from the database
            company = Company.query.filter_by(id=company_id).first()

            new_product = Product(
                description, type, category, cost, price, status, provider, company)

            db.session.add(new_product)
            db.session.commit()
            flash('¡Producto añadido con éxito!')
            return redirect(url_for('product.get_product'))

        except BadRequestKeyError as err:
            flash(f'Error: {str(err)}', category='error')
            return redirect(url_for('product.create_product'))

    company = Company.query.all()
    providers = Provider.query.all()
    if g.role == 'Administrador':
        return render_template('admin/products/product/create.html', company=company, providers=providers)
    else:
        return render_template('views/products/product/create.html', company=company, providers=providers)


@product.route("/update/<int:id>", methods=["GET", "POST"])
@set_role
def update_product(id, user=None):
    product = Product.query.get_or_404(id)

    if request.method == "POST":
        description = request.form['description']
        type = request.form['type']
        category = request.form['category']
        cost = request.form['cost']
        price = request.form['price']
        status = request.form['status']

        product.description = description
        product.type = type
        product.category = category
        product.cost = cost
        product.price = price
        product.status = status

        db.session.commit()

        flash('¡Producto actualizado con éxito!')
        return redirect(url_for('product.get_product'))

    if g.role == 'Administrador':
        return render_template('admin/products/product/update.html', product=product)
    else:
        return render_template('views/products/product/update.html', product=product)


@product.route("/delete/<int:id>", methods=["GET"])
@set_role
def delete_product(id, user=None):
    product = Product.query.get(id)

    if not product:
        flash('Producto no encontrado', category='error')
        return redirect(url_for('product.get_product'))

    try:
        db.session.delete(product)
        db.session.commit()

        flash('¡Producto eliminado con éxito!')
        return redirect(url_for('product.get_product'))

    except Exception as err:
        flash(
            f'Error al eliminar el producto: {str(err)}', category='error')
        return redirect(url_for('product.get_product'))

apps/templates/views/products/inventory/create.html
{% extends 'layout.html' %}
{% set current_page = 'Productos' %}
<h2>{% block title %}Nuevo Producto en Inventario{% endblock %}</h2>

{% block content %}
<!-- Page Heading -->
<div class="d-sm-flex justify-content-end mb-4">
  <h1 class="h1 mb-0 text-gray-800 flex-grow-1">Inventario</h1>
  <a href="{{url_for('inventory.get_inventory')}}" class="btn btn-primary btn-circle btn-lg m-1" title="Ver Todos los Productos en Inventario">
      <i class="fas fa-list"></i>
  </a>
</div>
<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{url_for('inventory.get_inventory')}}">Inventario</a></li>
    <li class="breadcrumb-item active" aria-current="page">Nuevo Producto en Inventario</li>
  </ol>
</nav>

<!-- Content Row -->
<div class="card o-hidden border-0 shadow-lg my-5">
  <div class="card-body p-0">
    <!-- Nested Row within Card Body -->
    <div class="row">
      <div class="col-lg-12">
        <div class="p-5">
          <div class="text-left">
            <h3 class="text-gray-900 mb-4">Nuevo Producto en Inventario</h3>
          </div>
          <form action="{{url_for('inventory.create_inventory')}}" method="POST">
            <div class="form-row">
              <div class="form-group col-md-12">
                <label for="">Producto</label>
                <select name="product_id" class="form-control js-example-basic-single">
                  <option value="" disabled selected></option>
                  {% for product in products%}
                  <option value="{{product.id}}">{{product.description}}</option>
                  {% endfor %}
                </select>
              </div>
            </div>
            <div class="form-row">
              <div class="form-group col-md-6">
                <label for="min_stock">Stock Mínimo</label>
                <input type="number" name="min_stock" class="form-control rounded-imput">
              </div>
              <div class="form-group col-md-6">
                <label for="set_stock">Stock Actual</label>
                <input type="number" name="set_stock" class="form-control rounded-imput">
              </div>
            </div>
            <div class="form-row">
              <div class="form-group col-md-6">
                <label for="type">Tipo</label>
                <select name="type" class="form-control rounded-select">
                  <option value="" disabled selected></option>
                  <option value="Venta">Venta</option>
                  <option value="Almacén">Almacén</option>
                </select>
              </div>
              <div class="form-group col-md-6">
                <label for="location">Ubicación</label>
                <input type="text" name="location" class="form-control rounded-imput">
              </div>
            </div>
            <div class="col-12 text-center">
              <button class="btn btn-primary col-6 rounded-button" type="submit">Crear</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

apps/templates/views/products/inventory/list.html
{% extends 'layout.html' %}
{% set current_page = 'Productos' %}
<h2>{% block title %}Inventario{% endblock %}</h2>

{% block content %}
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h1 mb-0 text-gray-800 d-flex">Inventario</h1>
    <a href="{{url_for('inventory.create_inventory')}}" class="btn btn-primary btn-circle btn-lg ml-auto" title="Nuevo Producto en Inventario">
        <i class="fa fa-plus" aria-hidden="true"></i>
    </a>
</div>
<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">Inventario</li>
    </ol>
</nav>
<!-- Content Row -->

<!-- DataTales Example -->
<div class="card shadow mb-5">
    <div class="card-header py-2">
        <h3 class="text-gray-900 mb-4">Productos en Inventario</h3>
    </div>
    <div class="card-body table-custom">
        <div class="table-responsive">
            <table class="table" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th class="th-sm">Producto
                        </th>
                        <th class="th-sm">Stock Mínimo
                        </th>
                        <th class="th-sm">Stock Actual
                        </th>
                        <th class="th-sm">Tipo
                        </th>
                        <th class="th-sm">Ubicación
                        </th>
                        <th class="th-sm">Creado
                        </th>
                        <th class="th-sm">Actualizado
                        </th>
                        <th class="th-sm">Acciones
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for inventory in inventory%}
                    <tr>
                        <td>{{inventory.product}}</td>
                        <td>{{inventory.min_stock}}</td>
                        <td>{{inventory.set_stock}}</td>
                        <td>{{inventory.type}}</td>
                        <td>{{inventory.location}}</td>
                        <td>{{inventory.created}}</td>
                        <td>{{inventory.updated}}</td>
                        <td>
                            <button class="btn  btn-sm btn-primary" onclick="location.href='{{ url_for('inventory.update_inventory', id=inventory.id) }}'" title="Editar">
                                <i class="fa fa-edit"></i>
                            </button>

                            <button class="btn btn-sm btn-danger"
                                onclick="location.href='{{ url_for('inventory.delete_inventory', id=inventory.id) }}'" title="Eliminar">
                                <i class="fa fa-trash"></i>
                            </button>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- </div> -->

{% endblock %}

apps/templates/views/products/inventory/update.html
{% extends 'layout.html' %}
{% set current_page = 'Productos' %}
<h2>{% block title %}Editar Producto en Inventario{% endblock %}</h2>

{% block content %}
<!-- Page Heading -->
<div class="d-sm-flex justify-content-end mb-4">
  <h1 class="h1 mb-0 text-gray-800 flex-grow-1">Inventario</h1>
  <a href="{{url_for('inventory.get_inventory')}}" class="btn btn-primary btn-circle btn-lg m-1" title="Ver Todos los Productos en Inventario">
      <i class="fas fa-list"></i>
  </a>
</div>
<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{url_for('inventory.get_inventory')}}">Inventario</a></li>
    <li class="breadcrumb-item active" aria-current="page">Editar Producto en Inventario</li>
  </ol>
</nav>

<!-- Content Row -->
<div class="card o-hidden border-0 shadow-lg my-5">
  <div class="card-body p-0">
    <!-- Nested Row within Card Body -->
    <div class="row">
      <div class="col-lg-12">
        <div class="p-5">
          <div class="text-left">
            <h3 class="text-gray-900 mb-4">Editar Producto en Inventario</h3>
          </div>
          <form action="{{url_for('inventory.update_inventory', id=inventory.id)}}" method="POST">
            <div class="form-row">
              <div class="form-group col-md-12">
                <label for="">Producto</label>
                <select name="product_id" class="form-control js-example-basic-single" disabled>
                  <option value="{{inventory.product_id}}" selected>{{inventory.product}}</option>
                </select>
              </div>
            </div>
            <div class="form-row">
              <div class="form-group col-md-6">
                <label for="min_stock">Stock Mínimo</label>
                <input type="number" name="min_stock" class="form-control rounded-imput" value="{{inventory.min_stock}}">
              </div>
              <div class="form-group col-md-6">
                <label for="set_stock">Stock Actual</label>
                <input type="number" name="set_stock" class="form-control rounded-imput"  value="{{inventory.set_stock}}">
              </div>
            </div>
            <div class="form-row">
              <div class="form-group col-md-6">
                <label for="type">Tipo</label>
                <select name="type" class="form-control rounded-select">
                  <option value="" {% if not inventory.type %}selected{% endif %} disabled></option>
                  <option value="Venta" {% if inventory.type=="Venta" %}selected{% endif %}>Venta</option>
                  <option value="Almacen" {% if inventory.type=="Almacen" %}selected{% endif %}>Almacen</option>
                </select>
              </div>
              <div class="form-group col-md-6">
                <label for="location">Ubicación</label>
                <input type="text" name="location" class="form-control rounded-imput" value="{{inventory.location}}">
              </div>
            </div>
            <div class="col-12 text-center">
              <button class="btn btn-primary col-6 rounded-button" type="submit">Actualizar</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}