apps/models/vehicle_reception.py
from datetime import datetime
from apps import db
from .vehicle import Vehicle
from .employee import Employee


class VehicleReception(db.Model):
    __tablename__ = 'vehicle_receptions'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    order_num = db.Column(db.String(20), unique=True)
    reception_reason = db.Column(db.String(100), nullable=False)
    created = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated = db.Column(db.DateTime, nullable=False,
                        default=datetime.utcnow, onupdate=datetime.utcnow)
    vehicle_id = db.Column(db.Integer, db.ForeignKey(
        'vehicles.id', onupdate='RESTRICT', ondelete='CASCADE'))
    employee_id = db.Column(db.Integer, db.ForeignKey(
        'employees.id', onupdate='RESTRICT', ondelete='CASCADE'))
    vehicle = db.relationship('Vehicle', backref=db.backref(
        'vehicle_receptions', lazy=True))
    employee = db.relationship(
        'Employee', backref=db.backref('vehicle_receptions', lazy=True))

    def __init__(self, order_num, reception_reason, vehicle, employee):
        self.order_num = order_num
        self.reception_reason = reception_reason
        self.vehicle = vehicle
        self.employee = employee

    def __repr__(self):
        return f'Orden {self.order_num} {self.reception_reason} del {self.vehicle}'

    @staticmethod
    def numero_orden_existe_en_bd(order_num):
        # Verificar si el número de orden ya existe en la base de datos
        order = VehicleReception.query.filter_by(order_num=order_num).first()
        if order:
            return True
        else:
            return False


class VehicleReceptionDetail(db.Model):
    __tablename__ = 'vehicle_reception_details'

    id = db.Column(
        db.Integer, primary_key=True, autoincrement=True)
    problem_description = db.Column(db.Text, nullable=False)
    front_condition = db.Column(db.String(100), nullable=False)
    back_condition = db.Column(db.String(100), nullable=False)
    left_condition = db.Column(db.String(100), nullable=False)
    right_condition = db.Column(db.String(100), nullable=False)
    roof_condition = db.Column(db.String(100), nullable=False)
    accessories = db.Column(db.String(100), nullable=False)
    tools = db.Column(db.String(100), nullable=False)
    objects = db.Column(db.String(100), nullable=False)
    created = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated = db.Column(db.DateTime, nullable=False,
                        default=datetime.utcnow, onupdate=datetime.utcnow)
    vehicle_reception_id = db.Column(
        db.Integer, db.ForeignKey('vehicle_receptions.id'))

    # Constructor
    def __init__(self, problem_description, front_condition, back_condition, left_condition, right_condition, roof_condition, accessories, tools, objects, vehicle_reception_id):
        self.problem_description = problem_description
        self.front_condition = front_condition
        self.back_condition = back_condition
        self.left_condition = left_condition
        self.right_condition = right_condition
        self.roof_condition = roof_condition
        self.accessories = accessories
        self.tools = tools
        self.objects = objects
        self.created = datetime.utcnow()
        self.updated = datetime.utcnow()
        self.vehicle_reception_id = vehicle_reception_id

apps/routes/vehicle_reception.py
from .auth import set_role
from flask import (
    render_template, Blueprint, flash, g, redirect, request, session, url_for
)
# Importar el contador
from itertools import count
from werkzeug.security import generate_password_hash


from sqlalchemy import func
from apps.models.vehicle_reception import VehicleReception, VehicleReceptionDetail
from apps.models.vehicle import Vehicle
from apps.models.employee import Employee
from apps import db

vehicle_reception = Blueprint(
    'vehicle_reception', __name__, url_prefix='/vehicle_reception')


@vehicle_reception.route("/list")
# función para verificar el rol del usuario
@set_role
def get_vehicle_reception(user=None):
    vehicle_reception = VehicleReception.query.all()
    vehicle_reception_detail = VehicleReceptionDetail.query.all()
    if g.role == 'Administrador':
        return render_template('admin/workshop/vehiclereception/list.html', vehicle_reception=vehicle_reception, vehicle_reception_detail=vehicle_reception_detail)
    else:
        return render_template('views/workshop/vehiclereception/list.html', vehicle_reception=vehicle_reception, vehicle_reception_detail=vehicle_reception_detail)


# Crear un contador que inicie en 100
# order_num_counter = count(start=100)


@vehicle_reception.route("/create", methods=['GET', 'POST'])
@set_role
def create_vehicle_reception(user=None):
    if request.method == 'POST':
        reception_reason = request.form['reception_reason']
        vehicle_id = request.form['vehicle_id']
        employee_id = request.form['employee_id']
        # Campos Detalle
        problem_description = request.form['problem_description']
        front_condition = request.form['front_condition']
        back_condition = request.form['back_condition']
        left_condition = request.form['left_condition']
        right_condition = request.form['right_condition']
        roof_condition = request.form['roof_condition']
        accessories = request.form['accessories']
        tools = request.form['tools']
        objects = request.form['objects']

        # Generar el order_num con prefijo "RV-"
        # order_num = "RV-" + str(next(order_num_counter))

        # Generar un nuevo número de orden
        # Crear un contador que inicie en 100
        order_num_counter_service = count(start=100)
        order_num = "RV-" + str(next(order_num_counter_service))

        # Verificar si el número de orden ya existe en la base de datos
        while VehicleReception.numero_orden_existe_en_bd(order_num):
            order_num = "RV-" + str(next(order_num_counter_service))

        # fetch the vehicle name from the database
        vehicle = Vehicle.query.filter_by(id=vehicle_id).first()

        # fetch the user name from the database
        employee = Employee.query.filter_by(id=employee_id).first()

        new_vehicle_reception = VehicleReception(order_num=order_num, reception_reason=reception_reason, vehicle=vehicle,
                                                 employee=employee)

        db.session.add(new_vehicle_reception)
        db.session.commit()

        # Obtener id de la ultima recepcion
        max_id = db.session.query(func.max(VehicleReception.id)).scalar()

        # Insertar Detalle
        new_vehicle_reception_detail = VehicleReceptionDetail(problem_description=problem_description, front_condition=front_condition, back_condition=back_condition, left_condition=left_condition,
                                                              right_condition=right_condition, roof_condition=roof_condition, accessories=accessories, tools=tools, objects=objects, vehicle_reception_id=max_id)
        db.session.add(new_vehicle_reception_detail)
        db.session.commit()

        flash('¡Recepción de Vehículo añadida con éxito!')
    vehicle = Vehicle.query.all()
    employee = Employee.query.filter(Employee.position!="Mecánico").all()
    vehicle_reception = VehicleReception.query.all()
    if g.role == 'Administrador':
        return render_template('admin/workshop/vehiclereception/create.html', vehicle=vehicle, employee=employee, vehicle_reception=vehicle_reception)
    else:
        return render_template('views/workshop/vehiclereception/create.html', vehicle=vehicle, employee=employee, vehicle_reception=vehicle_reception)


@vehicle_reception.route("/update/<int:id>", methods=["GET", "POST"])
@set_role
def update_vehicle_reception(id, user=None):
    vehicle_reception = VehicleReception.query.get(id)
    vehicle_reception_detail = VehicleReceptionDetail.query.filter_by(
        vehicle_reception_id=id).first()

    if request.method == 'POST':
        reception_reason = request.form['reception_reason']

        # Detalle de Recepción
        problem_description = request.form['problem_description']
        front_condition = request.form['front_condition']
        back_condition = request.form['back_condition']
        left_condition = request.form['left_condition']
        right_condition = request.form['right_condition']
        roof_condition = request.form['roof_condition']
        accessories = request.form['accessories']
        tools = request.form['tools']
        objects = request.form['objects']

        # Actualizar la recepción de vehículo existente en la base de datos
        vehicle_reception.reception_reason = reception_reason

        # Actualizar el detalle de la recepción de vehículo existente en la base de datos
        vehicle_reception_detail.problem_description = problem_description
        vehicle_reception_detail.front_condition = front_condition
        vehicle_reception_detail.back_condition = back_condition
        vehicle_reception_detail.left_condition = left_condition
        vehicle_reception_detail.right_condition = right_condition
        vehicle_reception_detail.roof_condition = roof_condition
        vehicle_reception_detail.accessories = accessories
        vehicle_reception_detail.tools = tools
        vehicle_reception_detail.objects = objects

        db.session.commit()

        flash('¡Recepción de Vehículo actualizada con éxito!')
        return redirect(url_for('vehicle_reception.get_vehicle_reception'))

    vehicle = Vehicle.query.all()
    employee = Employee.query.all()
    # print(
    #     f' DETALLES RECEPCION VEHICLE: {vehicle_reception_detail.problem_description}')
    if g.role == 'Administrador':
        return render_template('admin/workshop/vehiclereception/update.html', vehicle_reception=vehicle_reception, vehicle_reception_detail=vehicle_reception_detail, vehicle=vehicle, employee=employee)
    else:
        return render_template('views/workshop/vehiclereception/update.html', vehicle_reception=vehicle_reception, vehicle_reception_detail=vehicle_reception_detail, vehicle=vehicle, employee=employee)


# Delete
@vehicle_reception.route("/delete/<id>", methods=["GET"])
@set_role
def delete_vehicle_reception(id, user=None):
    vehicle_reception = VehicleReception.query.get(id)

    if not vehicle_reception:
        flash('Recepción de Vehículo no encontrada', category='error')
        return redirect(url_for('vehicle_reception.get_vehicle_reception'))

    try:
        # Obtener los registros relacionados en la tabla vehicle_reception_details
        vehicle_reception_details = VehicleReceptionDetail.query.filter_by(
            vehicle_reception_id=id).all()

        # Eliminar los registros en la tabla vehicle_reception_details
        for vehicle_reception_detail in vehicle_reception_details:
            db.session.delete(vehicle_reception_detail)

        # Confirmar los cambios en la base de datos
        db.session.commit()

        # Eliminar la recepción de vehículo
        db.session.delete(vehicle_reception)
        db.session.commit()

        flash('¡Recepción de Vehículo eliminada con éxito!')
        return redirect(url_for('vehicle_reception.get_vehicle_reception'))

    except Exception as err:
        db.session.rollback()  # Deshacer los cambios en caso de error
        flash(
            f'Error al eliminar la Recepción de Vehículo: {str(err)}', category='error')
        return redirect(url_for('vehicle_reception.get_vehicle_reception'))

apps/templates/views/workshop/vehiclereception/create.html
{% extends 'layout.html' %}
{% set current_page = 'Taller' %}
<h2>{% block title %}Recepción de Vehículos{% endblock %}</h2>

{% block content %}
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h1 mb-0 text-gray-800 d-flex">Recepción de Vehículos</h1>
    <a href="{{url_for('vehicle_reception.get_vehicle_reception')}}" class="btn btn-primary btn-circle btn-lg ml-auto"
        title="Ver Historial de Recepción de Vehículos">
        <i class="fa fa-list" aria-hidden="true"></i>
    </a>
</div>
<br>
<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{url_for('vehicle_reception.get_vehicle_reception')}}">Recepción de
            Vehículos</a></li>
        <li class="breadcrumb-item active" aria-current="page">Nueva Recepción de Vehículo</li>
    </ol>
</nav>

<!-- Content Row -->
<div class="card o-hidden border-0 shadow-lg my-5">
    <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
            <div class="col-lg-12">
                <div class="p-5">
                    <div class="text-left">
                        <h3 class="text-gray-900 mb-4">Nueva Recepción de Vehículo</h3>
                    </div>
                    <form action="{{url_for('vehicle_reception.create_vehicle_reception')}}" method="POST">
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <label for="employee_id">Generada por</label>
                                <select name="employee_id" class="form-control js-example-basic-single">
                                    <option value="" selected disabled></option>
                                    {% for employee in employee%}
                                    <option value="{{employee.id}}">{{employee.first_name}} {{employee.last_name}}
                                    </option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <label for="vehicle_id">Vehículo</label>
                                <select name="vehicle_id" class="form-control js-example-basic-single">
                                    <option value="" selected disabled></option>
                                    {% for vehicle in vehicle%}
                                    <option value="{{vehicle.id}}">{{vehicle.brand}} {{vehicle.model}} {{vehicle.year}}
                                        {{vehicle.plate_number}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <label for="reception_reason">Motivo de Recepción</label>
                                <input type="text" name="reception_reason" class="form-control rounded-imput">
                            </div>
                        </div>
                        <h3 class="text-gray-900 mb-4">Detalle de Recepción</h3>
                        <blockquote>Describe las condiciones en la que se recibió el vehículo y si se encontraron
                            algunas pertenencias en su interior.</blockquote>
                        <br>
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <label for="problem_description">Descripción de Recepción</label>
                                <input type="text" name="problem_description" class="form-control rounded-imput" />
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="front_condition">Condición Frontal</label>
                                <input type="text" name="front_condition" class="form-control rounded-imput""></input>
                            </div>
                            <div class=" form-group col-md-6">
                                <label for="back_condition">Condición Trasera</label>
                                <input type="text" name="back_condition" class="form-control rounded-imput"></input>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="left_condition">Condición Lateral Izquierda</label>
                                <input type="text" name="left_condition" class="form-control rounded-imput"></input>
                            </div>
                            <div class="form-group col-md-6">
                                <label for="right_condition">Condición Lateral Derecha</label>
                                <input name="right_condition" type="text" class="form-control rounded-imput"></input>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="roof_condition">Condición de Tejado</label>
                                <input type="text" name="roof_condition" class="form-control rounded-imput"></input>
                            </div>
                            <div class="form-group col-md-6">
                                <label for="accessories">Accesorios en el Vehículo</label>
                                <input name="accessories" type="text" class="form-control rounded-imput"></input>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="tools">Herramientas en el Vehículo</label>
                                <input name="tools" type="text" class="form-control rounded-imput"></input>
                            </div>
                            <div class="form-group col-md-6">
                                <label for="objects">Pertenencias en el Vehículo</label>
                                <input name="objects" type="text" class="form-control rounded-imput"></input>
                            </div>
                        </div>
                        <div class="col-12 text-center">
                            <button class="btn btn-primary col-6 rounded-button" type="submit">Crear</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    {% endblock %}

apps/templates/views/workshop/vehiclereception/list.html
{% extends 'layout.html' %}
{% set current_page = 'Taller' %}
<h2>{% block title %}Historial de Recepción de Vehículos{% endblock %}</h2>

{% block content %}
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h1 mb-0 text-gray-800 flex-grow-1">Recepción de Vehículos</h1>
    <a href="{{url_for('vehicle_reception.create_vehicle_reception')}}" class="btn btn-primary btn-circle btn-lg ml-auto" title="Nueva Recepción de Vehículo">
        <i class="fa fa-plus" aria-hidden="true"></i>
    </a>
</div>
<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">Recepción de Vehículos</li>
    </ol>
</nav>
<!-- Content Row -->

<!-- DataTales Example -->
<div class="card shadow mb-5">
    <div class="card-header py-2">
        <h3 class="text-gray-900 mb-4">Historial de Recepción de Vehículos</h3>
    </div>
    <div class="card-body table-custom">
        <div class="table-responsive">
            <blockquote>Pulsa en "Editar" en la recepción deseada para ver más información.</blockquote>
            <table class="table" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>No. de Orden</th>
                        <th>Vehículo</th>
                        <th>Motivo de Recepción</th>
                        <th>Atendida por</th>
                        <th>Registrada</th>
                        <th>Actualizada</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for vehicle_reception in vehicle_reception%}
                    <tr>
                        <td>{{vehicle_reception.order_num}}</td>
                        <td>{{vehicle_reception.vehicle}}</td>
                        <td>{{vehicle_reception.reception_reason}}</td>
                        <td>{{vehicle_reception.employee}}</td>
                        <td>{{vehicle_reception.created}}</td>
                        <td>{{vehicle_reception.updated}}</td>
                        <td>
                            <button class="btn  btn-sm btn-primary"
                                onclick="location.href='{{ url_for('vehicle_reception.update_vehicle_reception', id=vehicle_reception.id) }}'" title="Editar">
                                <i class="fa fa-edit"></i>
                            </button>
                            <button class="btn btn-sm btn-danger"
                                onclick="location.href='{{ url_for('vehicle_reception.delete_vehicle_reception', id=vehicle_reception.id) }}'" title="Eliminar">
                                <i class="fa fa-trash"></i>
                            </button>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- </div> -->

{% endblock %}

apps/templates/views/workshop/vehiclereception/update.html
{% extends 'layout.html' %}
{% set current_page = 'Taller' %}
<h2>{% block title %}Editar Recepción de Vehículo{% endblock %}</h2>

{% block content %}
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h1 mb-0 text-gray-800 d-flex">Recepción de Vehículos</h1>
    <a href="{{url_for('vehicle_reception.get_vehicle_reception')}}" class="btn btn-primary btn-circle btn-lg ml-auto">
        <i class="fa fa-list" aria-hidden="true"></i>
    </a>
</div>
<br>
<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{url_for('vehicle_reception.get_vehicle_reception')}}">Recepción de
            Vehículos</a></li>
        <li class="breadcrumb-item active" aria-current="page">Editar Recepción</li>
    </ol>
</nav>

<!-- Content Row -->
<div class="card o-hidden border-0 shadow-lg my-5">
    <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
            <div class="col-lg-12">
                <div class="p-5">
                    <div class="text-left">
                        <h3 class="text-gray-900 mb-4">Editar Recepción de Vehículo</h3>
                    </div>
                    <form action="{{url_for('vehicle_reception.update_vehicle_reception', id=vehicle_reception.id)}}"
                        method="POST">
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <label for="employee_id">Generada por</label>
                                <select name="employee_id" class="form-control js-example-basic-single" disabled>
                                    <option value="{{vehicle_reception.employee_id}}" selected>
                                        {{vehicle_reception.employee}}</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <label for="vehicle_id">Vehículo</label>
                                <select name="vehicle_id" class="form-control js-example-basic-single" disabled>
                                    <option value="{{vehicle_reception.vehicle_id}}" selected>
                                        {{vehicle_reception.vehicle}}</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <label for="reception_reason">Motivo de Recepción</label>
                                <input type="text" name="reception_reason" class="form-control rounded-imput"
                                    value="{{vehicle_reception.reception_reason}}">
                            </div>
                        </div>
                        <h3 class="text-gray-900 mb-4">Detalle de Recepción</h3>
                        <blockquote>Describe las condiciones en la que se recibió el vehículo y si se encontraron
                            algunas pertenencias en su interior.</blockquote>
                        <br>
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <label for="problem_description">Descripción de Recepción</label>
                                <input type="text" name="problem_description" cols="1" rows="3"
                                    class="form-control rounded-imput"
                                    value="{{vehicle_reception_detail.problem_description}}" />
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="front_condition">Condición Frontal</label>
                                <input type="text" name="front_condition" class="form-control rounded-imput"
                                    value="{{vehicle_reception_detail.front_condition}}"></input>
                            </div>
                            <div class="form-group col-md-6">
                                <label for="back_condition">Condición Trasera</label>
                                <input type="text" name="back_condition" class="form-control rounded-imput"
                                    value="{{vehicle_reception_detail.back_condition}}"></input>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="left_condition">Condición Lateral Izquierda</label>
                                <input type="text" name="left_condition" class="form-control rounded-imput"
                                    value="{{vehicle_reception_detail.left_condition}}"></input>
                            </div>
                            <div class="form-group col-md-6">
                                <label for="right_condition">Condición Lateral Derecha</label>
                                <input name="right_condition" type="text" class="form-control rounded-imput"
                                    value="{{vehicle_reception_detail.right_condition}}"></input>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="roof_condition">Condición de Tejado</label>
                                <input type="text" name="roof_condition" class="form-control rounded-imput"
                                    value="{{vehicle_reception_detail.roof_condition}}"></input>
                            </div>
                            <div class="form-group col-md-6">
                                <label for="accessories">Accesorios en el Vehículo</label>
                                <input name="accessories" type="text" class="form-control rounded-imput"
                                    value="{{vehicle_reception_detail.accessories}}"></input>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="tools">Herramientas en el Vehículo</label>
                                <input name="tools" type="text" class="form-control rounded-imput"
                                    value="{{vehicle_reception_detail.tools}}"></input>
                            </div>
                            <div class="form-group col-md-6">
                                <label for="objects">Pertenencias en el Vehículo</label>
                                <input name="objects" type="text" class="form-control rounded-imput"
                                    value="{{vehicle_reception_detail.objects}}"></input>
                            </div>
                        </div>
                        <div class="col-12 text-center">
                            <button class="btn btn-primary col-6 rounded-button" type="submit">Actualizar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    {% endblock %}